hard_tabs = true
imports_granularity = "One"
blank_lines_upper_bound = 0
where_single_line = true
inline_attribute_width = 80
max_width = 80
error_on_line_overflow = true
error_on_unformatted = true
format_strings = true
short_array_element_width_threshold = 80
single_line_if_else_max_width = 80
single_line_let_else_max_width = 80
struct_lit_width = 80
struct_variant_width = 80
normalize_doc_attributes = true
