[[language]]
	name = "x86-64 Assembly Macro Compiler (AMC86)"
	scope = "main.amc86"
	file-types = ["amc", "amc86"]
	comment-tokens = ["//"]
	[language.auto-pairs]
		'"' = '"'
	[language.indent]
		unit = "\t"
		tab-width = 4
