#!/usr/bin/env bash
set -uo pipefail
source src/.sh/conf
type=$1
shift
value=()
case "$type" in
	label) value_type=$type;;
	*) value_type=var;;
esac
value+=("$(run "$value_type" "$1")")
shift
case "$type" in
	str) value+=("$(run str "$@")");;
	label) ;;
	*) value+=("$@");;
esac
case "$type" in
	label) printf 'label %s' "${value[*]}";;
	*) printf 'def %s %s' "${type:0:1}" "${value[*]}";;
esac
